name: s3_object_uploader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content into the runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' # install the python version needed

      - name: install python packages #install the required python packages
        run: |
          python -m pip install --upgrade pip
          pip install boto3
          pip install pytz
          pip install flask 
          pip install Flask-Limiter


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2    

      - name: export env variables #export required enviroment variables
        run: |
          export BUCKET_NAME='my-unique-yahoo-bucket-name-4klma1zs'
          export KMS_KEY_ID='577e9ffc-c830-483a-bf45-7c8ae1d60f1f'
          echo $BUCKET_NAME
          echo $KMS_KEY_ID
          

      - name: execute py script #execute python script
        run: |
          cd scripts
          python -c 'import object_uploader; object_uploader.upload_timestamp()'
          python3 object_uploader.py
